export const PROJECT = {
  name: "URL Intelligence Agent",
  version: "1.0.0",
  release: "Unified Intelligence Release",
  creator: "Vincenzo Picciuolo",
  company: "HRN Innovation Technologies Ltd",
  ecosystem: "HORNO",
  website: "https://horno.net",
  easy: "https://easy.horno.net",
  space: "https://space.horno.net",
  repo: "https://github.com/vpicciuolo/url-intelligence-agent",
  baseToolkit: "https://github.com/vpicciuolo/url-metadata-social-fetcher",
  x: ["https://x.com/vpicciuolo", "https://x.com/hornonetwork", "https://x.com/BeHotNow2026"]
} as const;

export const projectMeta = () => ({
  project: PROJECT.name,
  version: PROJECT.version,
  release: PROJECT.release,
  creator: PROJECT.creator,
  company: PROJECT.company,
  ecosystem: PROJECT.ecosystem,
  website: PROJECT.website,
  repository: PROJECT.repo
});

export function creditsLine(): string {
  return `${PROJECT.name} v${PROJECT.version} · ${PROJECT.company} · Founder & Lead Engineer: ${PROJECT.creator} · HORNO: ${PROJECT.website}`;
}

export function creditsBlock(): string {
  return [
    `Generated by ${PROJECT.name} v${PROJECT.version} — ${PROJECT.release}`,
    PROJECT.company,
    `Founder & Lead Engineer: ${PROJECT.creator}`,
    `HORNO ecosystem: ${PROJECT.website}`,
    `Easy HORNO: ${PROJECT.easy}`,
    `HORNO Space: ${PROJECT.space}`,
    `Open source: ${PROJECT.repo}`
  ].join("\n");
}

export function attributionObject() {
  return {
    generatedBy: PROJECT.name,
    version: PROJECT.version,
    release: PROJECT.release,
    company: PROJECT.company,
    creator: PROJECT.creator,
    ecosystem: PROJECT.ecosystem,
    website: PROJECT.website,
    repository: PROJECT.repo
  };
}
