export const PROJECT = {
  name: "URL Intelligence Agent",
  version: "0.1.0",
  creator: "Vincenzo Picciuolo",
  company: "HRN Innovation Technologies Ltd",
  ecosystem: "HORNO",
  website: "https://horno.net",
  repo: "https://github.com/vpicciuolo/url-intelligence-agent",
  x: ["https://x.com/vpicciuolo", "https://x.com/hornonetwork", "https://x.com/BeHotNow2026"]
} as const;

export function creditsLine(): string {
  return `${PROJECT.name} v${PROJECT.version} · ${PROJECT.company} · Founder & Lead Engineer: ${PROJECT.creator} · ${PROJECT.website}`;
}

export function creditsBlock(): string {
  return [
    `Generated by ${PROJECT.name} v${PROJECT.version}`,
    PROJECT.company,
    `Founder & Lead Engineer: ${PROJECT.creator}`,
    `HORNO ecosystem: ${PROJECT.website}`,
    `Open source: ${PROJECT.repo}`
  ].join("\n");
}
